# Generated by Django 2.0.5 on 2018-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente'), ('V', 'Vigente'), ('Re', 'Recibido'), ('Pe', 'Perdido')], default='P', max_length=2, verbose_name='Estado'),
        ),
    ]
